# Generated by Django 5.0.2 on 2024-02-22 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_ins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='security_policy_master',
            fields=[
                ('soft_delete_model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rms_ins.soft_delete_model')),
                ('ip_addr_category', models.CharField(blank=True, max_length=25, null=True)),
                ('ip_addr', models.GenericIPAddressField(null=True)),
                ('user_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            bases=('rms_ins.soft_delete_model',),
        ),
    ]
