# Generated by Django 5.0.2 on 2024-03-05 07:51

import django.db.models.deletion
import rms_ins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_ins', '0002_security_policy_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity_order_master',
            name='entity_order_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='sales_order_master',
            fields=[
                ('soft_delete_model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rms_ins.soft_delete_model')),
                ('po_no', models.CharField(blank=True, max_length=100, null=True)),
                ('po_file', models.FileField(null=True, upload_to=rms_ins.models.user_directory_path, verbose_name='')),
                ('po_dt', models.DateField(blank=True, null=True)),
                ('tax_exemption_no', models.TextField(blank=True, max_length=500, null=True)),
                ('delivery_dt', models.DateField(blank=True, null=True)),
                ('entity_order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rms_ins.entity_order_master')),
            ],
            bases=('rms_ins.soft_delete_model',),
        ),
    ]
