# Generated by Django 5.0.2 on 2024-03-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_ins', '0003_entity_order_master_entity_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity_order_master',
            name='indent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity_order_master',
            name='indent_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entity_order_master',
            name='quotation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity_order_master',
            name='quotation_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
