# Generated by Django 5.0.3 on 2024-04-12 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_ins', '0005_gmr_master_gmr_detail_goods_movement_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gmr_detail',
            old_name='Basic_Rate',
            new_name='basic_rate',
        ),
        migrations.RenameField(
            model_name='gmr_detail',
            old_name='Deduction_qty',
            new_name='deduction_qty',
        ),
        migrations.RenameField(
            model_name='gmr_detail',
            old_name='Received_qty',
            new_name='received_qty',
        ),
        migrations.RenameField(
            model_name='gmr_detail',
            old_name='Tax_perc',
            new_name='tax_perc',
        ),
        migrations.RenameField(
            model_name='gmr_detail',
            old_name='Taxable_amt',
            new_name='taxable_amt',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='Prefix',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='authorised_by',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='checkin_no',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='checkout_no',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='consignee_details',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='customer_vendor',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='dc_dt',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='dc_no',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='driver_mobile_no',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='in_date',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='in_time',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='invoice_details',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='is_checkin',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='is_checkout',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='measurement_taken_by',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='order',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='out_date',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='out_time',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='site_plant',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='sl_time',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='status',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='transporter_name',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='user_remarks',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='vehicle_others',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='weighment_name',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='weighment_slip_date',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='weighment_slip_no',
        ),
        migrations.RemoveField(
            model_name='gmr_master',
            name='weighment_slip_time',
        ),
        migrations.CreateModel(
            name='equipment_master',
            fields=[
                ('soft_delete_model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rms_ins.soft_delete_model')),
                ('is_tax_applicable', models.IntegerField(default=0)),
                ('equip_name', models.CharField(max_length=100)),
                ('capacity', models.FloatField(default=0)),
                ('mode', models.CharField(max_length=10)),
                ('fuel_type', models.CharField(max_length=15)),
                ('insurance_date', models.DateField(blank=True, null=True)),
                ('permit_date', models.DateField(blank=True, null=True)),
                ('fc_date', models.DateField(blank=True, null=True)),
                ('is_equip_ready', models.IntegerField(default=0)),
                ('meter_status', models.IntegerField(default=0)),
                ('meter_reading', models.IntegerField(default=0)),
                ('co_open_km', models.IntegerField(default=0)),
                ('equip_open_hm', models.IntegerField(default=0)),
                ('co_open_hm', models.IntegerField(default=0)),
                ('user_remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('status', models.IntegerField(default=1)),
                ('entity_vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rms_ins.entity_master')),
                ('equip_grp_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equip_grp_code', to='rms_ins.entity_master')),
                ('equip_tax_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equip_tax_code', to='rms_ins.taxform_master')),
            ],
            bases=('rms_ins.soft_delete_model',),
        ),
    ]
