# Generated by Django 5.0.3 on 2024-04-13 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_ins', '0006_rename_basic_rate_gmr_detail_basic_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmr_master',
            name='Prefix',
            field=models.CharField(default='grn/src/2024-2026', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='checkout_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='consignee_details',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='customer_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_vendor', to='rms_ins.entity_master'),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='driver_mobile_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='invoice_details',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rms_ins.entity_order_master'),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='site_plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_plant', to='rms_ins.entity_master'),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='sl_time',
            field=models.TimeField(default='09:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='transporter_name',
            field=models.CharField(default='mohana', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='vehicle_others',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='vehicle_own',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rms_ins.equipment_master'),
        ),
    ]
