# Generated by Django 5.0.3 on 2024-04-13 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_ins', '0007_gmr_master_prefix_gmr_master_checkout_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmr_master',
            name='authorised_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='checkin_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        # migrations.AddField(
        #     model_name='gmr_master',
        #     name='dc_dt',
        #     field=models.DateField(default='13.04.2024'),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='gmr_master',
            name='dc_no',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rms_ins.sales_purchase_master'),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='is_checkin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='is_checkout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='lr_dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='lr_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='measurement_taken_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='received_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='transport_mode',
            field=models.CharField(default='own', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='user_remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='weighment_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='weighment_slip_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='weighment_slip_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gmr_master',
            name='weighment_slip_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
