# Generated by Django 5.0.3 on 2024-04-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_ins', '0008_gmr_master_authorised_by_gmr_master_checkin_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmr_master',
            name='dc_dt',
            field=models.DateField(default='2024-04-13'),
            preserve_default=False,
        ),
    ]
