# Generated by Django 5.0.3 on 2024-04-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms_ins', '0009_gmr_master_dc_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gmr_master',
            old_name='Prefix',
            new_name='prefix',
        ),
    ]
